package com.elifersumer.myapplication.GetAccountList.Response

class Account {
    var IsBlockedAccount : Boolean?=null
    var BlockageType : String?=null
    var IsPartialBlockedAccount:Boolean?=null
    var IsAggregatedAccount:Boolean?=null
    var AccountSuffix:Double?=null
    var BranchCode : Double?=null
    var CustomerNo:Int?=null
    var ProductCode:String?=null
    var OriginalProductCode:String?=null
    var ProjectCode : String ?=null
    var ShortName :String ?= null
    var IsClosed:Boolean?=null
    var IsDisplayedOnInternet:Boolean?=null
    var IsAutoInvested:Boolean?=null
    var CurrencyCode:String?=null
    var AnalysisCode : String?=null
    var ReceivableInterestRate : Double?=null
    var DebtInterestRate:Double?=null
    var AmountOfBalance:Double?=null
    var AmountOfBalanceGross:Double?=null
    var AvailableCaptainBalance:Double?=null
    var AvailableBalance:Double?=null
    var AvailableBalanceGross : Double?=null
    var PreviousDateBalanceGross:Double?=null
    var SCCode : List<String>?=null
    var IsPersonnelAccount : Boolean?=null
    var AccountName : String?=null
    var IBANNo : String?=null
    var CaptainAccountFundBalance : Int?=null
    var CaptainAccountBalance : Int?=null
    var AvailableCreditDepositBalance : Int?=null
    var CaptainAccountFlag : Boolean?=null
    var ModernAccountFlag : Boolean?=null
    var ModernAccountMinumumBalance : Int?=null
    var DormantAccountFlag : Boolean?=null
    var ValueDate : String?=null
    var MaturityDate : String?=null
    var AccountClosingDate : String?=null
    var AccountClosingUserCode : String?=null
    var AccountOpenningDate : String?=null
    var AccountOpenningUserCode : String?=null
    var ReverseBalancePositionFlag : String?=null
    var ReverseBalanceAbilityFlag : String?=null
    var CDAFlag : String?=null
    var BlockageCodeName : String?=null
    var BlockageName : String?=null
    var BlockageReasonCode : String?=null
    var BlockageReasonCodeName : String?=null
    var BlockageExplanation : String?=null
    var BlockageUserCode : String?=null
    var BlockageAmount : Int?=null
    var BlockageMaturityDate : String?=null
    var BlockageValueDate : String?=null
    var PreviousDateBalance : Int?=null
    var TotalPartialBlockageAmount : Int?=null
    var DebitAccuredInterestAmountForKMH : Int?=null
    var CaptainAvailableBalance : Int?=null
    var HasSchoolPayment : String?=null
    var AvailableCreditDeposit : Int?=null
    var BatchDate : String?=null
    var DelayCount : Int?=null
    var MinPaymentAmount : Int?=null
    var LastPaymentDate : String?=null
    var CDALimit : Int?=null
    var DebitAccruedInterestAmount : Int?=null
    var DayToMaturity : Int?=null
    var CreditInterestRate : Int?=null
    var NetInterestAmount : Int?=null
    var CreditAccruedInterestAmount : Int?=null
    var RollType : String?=null
    var IsSuitableForIncomeAndOut : Boolean?=null
    var IsPos : Boolean?=null
    var CdaCashSuffix : Int?=null
    var CdaAvailableLimit : Int?=null
    var IsDormantAccount : Boolean?=null
    var RateType : String?=null
    var CdaChangeReasonCode : String?=null
    var CdaReasonDescription : String?=null
    var TransactionCodeList : String?=null
    var AdditionalTufeRate : Int?=null
    var TransferrableBlockageAmount : Int?=null
    var IsFreeZoneAccount : Boolean?=null
}